controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

# https://control.ros.org/master/doc/ros2_controllers/diff_drive_controller/doc/userdoc.html
diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["amiga__left_wheel_front_joint", "amiga__left_wheel_rear_joint"]
    right_wheel_names: ["amiga__right_wheel_front_joint", "amiga__right_wheel_rear_joint"]
    wheel_separation: 1.0  # meters
    wheel_radius: 0.25      # meters

    wheel_separation_multiplier: 1.4
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    use_stamped_vel: true

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: amiga__base
    pose_covariance_diagonal : [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]

    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 2.0
    linear.x.min_velocity: -2.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 0.5
    angular.z.min_velocity: -0.5
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0